FROM nginx:1.19.3-alpine
COPY index.html /usr/share/nginx/html

#docker build -t image-3  -f Dockerfile .
#docker run -d -p 8080:80 --name container-3 --rm -v static_content:/usr/share/nginx/html image-3